### ISSUE TITLE
FSLC visualization

### ISSUE THREAD

**Issue by Aaamazing** [yuehuang2023/cryoNeFEN#11]
Hello! How can I reproduce your FSLC view, such as Fig. 2f? Is there any code available for reference?
![a2a92a57eeea53d42441f2b496cac61](https://github.com/user-attachments/assets/8a5ca7ce-d0ff-4497-a30c-e4f14e1e9d13)

**Comment by yuehuang2023** [comment]
You can refer to the function `calc_fslc` in `analysis.py`. This figure was plotted with `healpy`.

**Comment by Aaamazing** [comment]
Thank you!
