### ISSUE TITLE
problem about 10049 C1 local resolution reproduction

### ISSUE THREAD

**Issue by Rich-XGK** [yuehuang2023/cryoNeFEN#4]
Dear Authors,

Thank you very much for your excellent work! We have downloaded the checkpoint and MRC file for 10049 that you uploaded and are attempting to reproduce the results shown in Figure 4.b of your paper, specifically regarding the local resolution of 10049 under C1 symmetry. We are using RELION software, and the commands we used are shown below. However, our results have significant discrepancies from those presented in your paper. Could you please share how you performed the calculations, what software you used, and if there were any additional settings or parameters involved? If possible, we would greatly appreciate your guidance. Thank you very much!

‘
cd /data/WorkSpace/relion/build/bin
./relion_postprocess --i /data/WorkSpace/local_reselution/cryoNeFEN_maps/vol_C1_it023_half1_loosemask.192.mrc --i2 /data/WorkSpace/local_reselution/cryoNeFEN_maps/vol_C1_it023_half2_loosemask.192.mrc --o /data/WorkSpace/local_reselution/cryoNeFEN_maps/cryoNeFEN_vol_C1_it023_ --locres map
’
<img width="496" alt="截屏2024-08-29 11 24 01" src="https://github.com/user-attachments/assets/aaa4f10d-d733-4a12-b035-e0b175ee413b">
<img width="496" alt="截屏2024-08-29 11 24 12" src="https://github.com/user-attachments/assets/dce15cf3-77d4-4c3a-be5b-aa1d6828267b">
<img width="517" alt="截屏2024-08-29 11 24 24" src="https://github.com/user-attachments/assets/3edc7627-35ac-4ef8-9f83-61f21b6bfd5b">

**Comment by yuehuang2023** [comment]
You may adjust the color bar in ChimeraX, and use the filtered map generated by Resmap in Relion.

**Comment by yuehuang2023** [comment]
In addition, the map should be sharpened by bfactor.

**Comment by Rich-XGK** [comment]
Sorry to bother you again, but I am not quite sure what “the filtered map generated by Resmap in Relion” means. As far as I know, both Resmap and Relion can calculate local resolution, but could you please explain in more detail what “Resmap in Relion” specifically refers to?

**Comment by Rich-XGK** [comment]
Sorry to bother you! I understand now. I initially thought Resmap and Relion were separate, different software programs. I wasn’t aware that Resmap is implemented within Relion.

**Comment by yuehuang2023** [comment]
Refer to https://relion.readthedocs.io/en/release-3.1/SPA_tutorial/Validation.html, the filtered map is saved as 'LocalRes/polished/relion_locres_filtered.mrc'.

**Comment by yuehuang2023** [comment]
The mask is generated by cryoSPARC with 'homogeneous refine' job.

**Comment by yuehuang2023** [comment]
However, the mask has little effect on the resolution of cryonefen.

**Comment by Rich-XGK** [comment]
![DINGTALK_IM_3334446095](https://github.com/user-attachments/assets/2e6ad5b2-21e6-45c1-8f36-9208e2869127)
Apologize for bothering you again! How should these parameters be set to reproduce your results?

**Comment by Rich-XGK** [comment]
![Uploading DINGTALK_IM_3334446095.JPG…]()

**Comment by yuehuang2023** [comment]
Change the Use Resmap option to 'No', and tune the parameters of the Relion tab

**Comment by Rich-XGK** [comment]
If that's the case, it seems that the local resolution is still being calculated using Relion's own post_process. I think this somewhat conflicts with or creates ambiguity in your writing, especially the statement, "The local resolution is calculated with Resmap implemented with Relion." As shown in the figure, could you please explain this further? Thank you very much!!!
<img width="1103" alt="截屏2024-09-03 14 44 18" src="https://github.com/user-attachments/assets/239da6b1-bee7-4f22-bc88-5fce87557614">

**Comment by yuehuang2023** [comment]
Relion implements a wrapper to this program through the Local resolution job-type.

**Comment by Rich-XGK** [comment]
<img width="1306" alt="截屏2024-09-03 15 39 46" src="https://github.com/user-attachments/assets/e740d761-7b6e-4245-99b0-4851b5b4510d">
By using the following Relion command: ./relion_postprocess --i /data/WorkSpace/local_reselution/cryoNeFEN_maps/vol_C1_it023_half1_loosemask.192.mrc -o /data/WorkSpace/local_reselution/cryoNeFEN_maps/vol_C1_it023_half1_loosemask.192.bfactored.mrc --adhoc_bfac -120 --locres map, along with the MRC files you uploaded and the -120 bfactor parameter mentioned in the paper, we obtained results with similar details to those shown in your paper. We also adjusted the color bar to match your settings, but the colors of the local resolution still show significant differences.

**Comment by yuehuang2023** [comment]
Please compare the figures in the published paper, not this preprint version.

**Comment by Rich-XGK** [comment]
Thank you for your patient response! We have successfully reproduced the local resolution visualization results for 10049 from your final version of the paper. It’s truly excellent work, and we are deeply grateful for your significant contribution! However, we encountered some other issues during data processing, and I would greatly appreciate your guidance as I raise a new issue for your advice.
