### ISSUE TITLE
Visualization Issue with 10005 Dataset

### ISSUE THREAD

**Issue by Aaamazing** [yuehuang2023/cryoNeFEN#9]
We have encountered some questions regarding the visualization of the 10005 dataset. We used the volume results from the 10005 dataset you uploaded and applied bfactor=-100 for sharpening (as specified in the paper). The final results were visualized in ChimeraX, and we adjusted the threshold to make the images as consistent as possible with those in your paper.

However, we encountered an issue: in our reproduced results, there are many small scattered noise points in the periphery (as shown in the black box), whereas the images in your paper appear much cleaner. We would like to ask whether we may have missed any steps, or if additional filtering is required.

If it’s convenient, we would greatly appreciate any guidance or suggestions. Thank you very much for your help!
<img width="1138" alt="93b55e5b1bceee705abe9bc482d7143" src="https://github.com/user-attachments/assets/9d9061ca-a4d0-4bab-8acd-85907a42ec1b">
<img width="509" alt="154ca0320a3aaf8e14b4995dcd619f5" src="https://github.com/user-attachments/assets/60df9945-d578-4020-aad4-41ea5765ecf2">
<img width="482" alt="cacf5fc610b20016d2240ea31b1fc2b" src="https://github.com/user-attachments/assets/f84e3346-a355-4b97-8f18-344bfcc2a1c8">

**Comment by yuehuang2023** [comment]
You can use the 'hide dust' in ChimeraX.

**Comment by Aaamazing** [comment]
> You can use the 'hide dust' in ChimeraX.

Thank you very much! The issue has been resolved!
